// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwwbQ3QQWGD3wEXWA0i1se7ckNcBAdQWo',
    appId: '1:184014971834:web:4eb83776719fbd1b41f383',
    messagingSenderId: '184014971834',
    projectId: 'style-transfer-334ff',
    authDomain: 'style-transfer-334ff.firebaseapp.com',
    storageBucket: 'style-transfer-334ff.appspot.com',
    measurementId: 'G-LN9P782GFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALOzYO7PTwni27S2dAQnLhyynwYTe5aYg',
    appId: '1:184014971834:android:db17ae63b088f00d41f383',
    messagingSenderId: '184014971834',
    projectId: 'style-transfer-334ff',
    storageBucket: 'style-transfer-334ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRxF8oSWgPzFLS2oQAZDtVQuPZzARP_Qw',
    appId: '1:184014971834:ios:e3514940467c356a41f383',
    messagingSenderId: '184014971834',
    projectId: 'style-transfer-334ff',
    storageBucket: 'style-transfer-334ff.appspot.com',
    iosClientId: '184014971834-a5la6q05auqcle3rgigohdtmhjvei0bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.imageCombiner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRxF8oSWgPzFLS2oQAZDtVQuPZzARP_Qw',
    appId: '1:184014971834:ios:e3514940467c356a41f383',
    messagingSenderId: '184014971834',
    projectId: 'style-transfer-334ff',
    storageBucket: 'style-transfer-334ff.appspot.com',
    iosClientId: '184014971834-a5la6q05auqcle3rgigohdtmhjvei0bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.imageCombiner',
  );
}
